export const Sound = {
  hoboSinging1: 'hobo_singing_1',
  hoboSinging2: 'hobo_singing_2',
  hoboSinging3: 'hobo_singing_3',
  rejectMoney: 'reject_money',
  coinDrop1: 'coin_drop_1',
  coinDrop2: 'coin_drop_2',
  coinDrop3: 'coin_drop_3',
  peeHitSound1: 'sik_miejskie',
  peeHitSound2: 'sik_ziemia',
  manHit1: 'hit_man1',
  manHit2: 'hit_man2',
  womanHit1: 'hit_woman1',
  womanHit2: 'hit_woman2',
  drinkingVodka1: 'drinking_vodka_1',
  drinkingVodka2: 'drinking_vodka_2',
  drinkingVodka3: 'drinking_vodka_3',
  drinkingEnergy1: 'drinking_energy_1',
  drinkingEnergy2: 'drinking_energy_2',
  drinkingEnergy3: 'drinking_energy_3',
  drinkingEnergy4: 'drinking_energy_4',
  drinkingEnergy5: 'drinking_energy_5',
};
